### ISSUE TITLE
Problems of generating training data

### ISSUE THREAD

**Issue by whd14** [cselab/LED#1]
Sorry, I found a problem in running demonstration on FHN. After I run these scripts from 0_data_gen.py to 4_create_test_data.py, I found the folder Data\FHN\Data\train is still empty. There are only files in the folder of train_raw and val_raw.
Then, the code "4_AE.sh" also report errors of "No hdf5 datasets found", which means it needs a file in the folder Data\FHN\Data\train. 
Directly copying the file from train_raw to train still does not work. 
How to generate the correct file in the floder Data\FHN\Data\train?

**Comment by pvlachas** [comment]
Sorry for the late reply. For some reason I missed the notification.
Some lines on the script 2 were commented out. Should be resolved.
